package dreamsoftware.smartgridoptimizer.gui.panel;

public enum ModelValuesEnum {
	GENERATE_ENERGY_AGENTS, CONSUMPTION_ENERGY_AGENTS, BATTERY_AGENTS, WIND_POWER, LOAD, 
	SURPLUS, ADJUST_LOAD, TOTAL_BATTERY, POWER_SOLD, POWER_BOUGHT, TOTAL_SOLD, TOTAL_BOUGHT,
	CURRENT_PRICE, BUDGET;
}
